(() => {
  'use strict';
  const grid=document.getElementById('linkedin-posts'), status=document.getElementById('linkedin-status'), pagination=document.getElementById('linkedin-pagination');
  const prev=document.getElementById('linkedin-prev'), next=document.getElementById('linkedin-next'), counter=document.getElementById('linkedin-page-counter');
  if(!grid||!status||!pagination||!prev||!next||!counter)return;
  const company='https://www.linkedin.com/company/77574975/';
  const PAGE_SIZE=3; let posts=[],page=0;
  const safe=v=>{if(typeof v!=='string')return null;try{const u=new URL(v,location.origin);return u.protocol==='https:'?u.href:null}catch{return null}};
  const date=v=>{if(!v)return '';const n=Number(v),d=Number.isFinite(n)&&n>0?new Date(n<1e12?n*1000:n):new Date(v);return isNaN(d.getTime())?'':d.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})};
  const clean=v=>typeof v==='string'?v.replace(/\{hashtag\\?\|([^}]+)\}/gi,'$1').replace(/\\+#\|/g,'#').replace(/#\|/g,'#').replace(/\\+#/g,'#').replace(/\r\n/g,'\n').trim():'';
  function normalize(p){const images=(Array.isArray(p.images)?p.images:[]).map(safe).filter(Boolean),single=safe(p.imageUrl??p.image);if(single&&!images.includes(single))images.unshift(single);return {text:clean(typeof p.commentary==='string'?p.commentary:p.commentary?.text??p.text??''),date:date(p.publishedAt??p.createdAt??p.date),url:safe(p.url??p.permalink??p.linkedinUrl)??company,images,video:safe(p.videoUrl),mediaType:p.mediaType??'none'};}
  function media(p){if(p.video){const v=document.createElement('video');v.className='linkedin-card__image';v.src=p.video;v.controls=true;v.playsInline=true;v.preload='metadata';if(p.images[0])v.poster=p.images[0];return v;}if(!p.images.length)return null;const wrap=document.createElement('div');wrap.className='linkedin-card__gallery';const img=document.createElement('img');img.className='linkedin-card__image';img.loading='lazy';img.alt='ErsSoft LinkedIn post';wrap.append(img);let i=0;if(p.images.length>1){const controls=document.createElement('div');controls.className='linkedin-card__gallery-controls';const a=document.createElement('button'),b=document.createElement('button'),count=document.createElement('span');a.type=b.type='button';a.textContent='←';b.textContent='→';a.setAttribute('aria-label','Previous image');b.setAttribute('aria-label','Next image');controls.append(a,count,b);wrap.append(controls);a.onclick=()=>{if(i>0){i--;update()}};b.onclick=()=>{if(i<p.images.length-1){i++;update()}};function update(){img.src=p.images[i];count.textContent=`${i+1} / ${p.images.length}`;a.disabled=i===0;b.disabled=i===p.images.length-1;}update();}else img.src=p.images[0];return wrap;}
  function card(p){const el=document.createElement('article');el.className='linkedin-card';const m=media(p);if(m)el.append(m);const body=document.createElement('div');body.className='linkedin-card__body';const d=document.createElement('span');d.className='linkedin-card__date';d.textContent=p.date;const t=document.createElement('p');t.className='linkedin-card__text';t.textContent=p.text;const a=document.createElement('a');a.className='linkedin-card__link';a.href=p.url;a.target='_blank';a.rel='noopener noreferrer';a.textContent='View on LinkedIn ↗';body.append(d,t,a);el.append(body);return el;}
  function render(){grid.replaceChildren(...posts.slice(page*PAGE_SIZE,(page+1)*PAGE_SIZE).map(card));grid.hidden=false;const total=Math.ceil(posts.length/PAGE_SIZE);pagination.hidden=total<=1;counter.textContent=`${page+1} / ${total}`;prev.disabled=page===0;next.disabled=page>=total-1;}
  prev.onclick=()=>{if(page>0){page--;render()}};next.onclick=()=>{if((page+1)*PAGE_SIZE<posts.length){page++;render()}};
  fetch('/api/linkedin/posts',{headers:{Accept:'application/json'}}).then(async r=>{if(!r.ok)throw Error(`API ${r.status}`);return r.json()}).then(data=>{if(data.error)throw Error(data.error);const items=Array.isArray(data)?data:data.posts??data.elements??[];if(!Array.isArray(items))throw Error('Invalid API response');posts=items.map(normalize);if(!posts.length){status.textContent='No LinkedIn updates available at the moment.';return;}status.hidden=true;render()}).catch(e=>{console.error('LinkedIn loading error',e);status.textContent='LinkedIn updates are temporarily unavailable.'});
})();
